// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpyO6a6BxD9JVIcerNhEchDFxX7m9a9M',
    appId: '1:179093139757:web:a8c9d7fe3fcce04147a3a4',
    messagingSenderId: '179093139757',
    projectId: 'indie-commerce-75ccd',
    authDomain: 'indie-commerce-75ccd.firebaseapp.com',
    storageBucket: 'indie-commerce-75ccd.appspot.com',
    measurementId: 'G-8CWX90WGY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMf5pnx1FS9IFuQhUSCXAwcOD8kGmLFgQ',
    appId: '1:179093139757:android:6f49efc480a19a3547a3a4',
    messagingSenderId: '179093139757',
    projectId: 'indie-commerce-75ccd',
    storageBucket: 'indie-commerce-75ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzRAlBDa6i1fnsw7KwV8h7Vf-Dvat7IM',
    appId: '1:179093139757:ios:38239146cb39533247a3a4',
    messagingSenderId: '179093139757',
    projectId: 'indie-commerce-75ccd',
    storageBucket: 'indie-commerce-75ccd.appspot.com',
    iosBundleId: 'com.example.indieCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzRAlBDa6i1fnsw7KwV8h7Vf-Dvat7IM',
    appId: '1:179093139757:ios:38239146cb39533247a3a4',
    messagingSenderId: '179093139757',
    projectId: 'indie-commerce-75ccd',
    storageBucket: 'indie-commerce-75ccd.appspot.com',
    iosBundleId: 'com.example.indieCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZpyO6a6BxD9JVIcerNhEchDFxX7m9a9M',
    appId: '1:179093139757:web:71c2b8fbc0f744c247a3a4',
    messagingSenderId: '179093139757',
    projectId: 'indie-commerce-75ccd',
    authDomain: 'indie-commerce-75ccd.firebaseapp.com',
    storageBucket: 'indie-commerce-75ccd.appspot.com',
    measurementId: 'G-9PFBG828J8',
  );
}
